steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/camping-note/dev:latest', '.' , '-f', 'Dockerfile']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us.gcr.io/camping-note/dev:latest']