steps:
- name: 'us.gcr.io/cloud-builders/docker'
args: ['build', '-t', 'us.gcr.io/camping-note/dev:latest', '.']
- name: 'us.gcr.io/cloud-builders/docker'
args: ['push', 'us.gcr.io/camping-note/dev:latest']